FROM nginx
#RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Copy custom HTML content to the nginx html directory
COPY index.html /usr/share/nginx/html
# Copy custom Nginx configuration file
COPY hello.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]