
---
#horizontal pod autoscaller Auto Scale with HPA Based on CPU and Memory -  
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
  namespace: staging
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  targetCPUUtilizationPercentage: 50